/* ==========================================================================
   MCA_DATA — Fallback mock dataset used when FastAPI backend is offline.
   Shown on Vercel / static deployments.
   ========================================================================== */

const MCA_DATA = {
  companies: [
    { cin:"L72200MH1995PLC085624", legal_name:"TATA CONSULTANCY SERVICES LIMITED", name:"TATA CONSULTANCY SERVICES LIMITED", brand:"TCS", domain:"tcs.com", roc:"ROC Mumbai", incorporated:1995, company_class:"Public", capital:"₹500 Cr+", career_url:"https://www.tcs.com/careers", ats:"Custom/iON", status:"Active" },
    { cin:"U72200KA2013PTC097332", legal_name:"RAZORPAY SOFTWARE PRIVATE LIMITED", name:"RAZORPAY SOFTWARE PRIVATE LIMITED", brand:"Razorpay", domain:"razorpay.com", roc:"ROC Bangalore", incorporated:2013, company_class:"Private", capital:"₹100 Cr+", career_url:"https://boards.greenhouse.io/razorpaysoftwareprivatelimited", ats:"Greenhouse", status:"Active" },
    { cin:"U72200MH2007PTC173821", legal_name:"ONE97 COMMUNICATIONS LIMITED", name:"ONE97 COMMUNICATIONS LIMITED", brand:"Paytm", domain:"paytm.com", roc:"ROC Noida", incorporated:2007, company_class:"Public", capital:"₹400 Cr+", career_url:"https://jobs.lever.co/paytm", ats:"Lever", status:"Active" },
    { cin:"U72900TN2010PLC075256", legal_name:"FRESHWORKS INC INDIA PRIVATE LIMITED", name:"FRESHWORKS INC INDIA PRIVATE LIMITED", brand:"Freshworks", domain:"freshworks.com", roc:"ROC Chennai", incorporated:2010, company_class:"Private", capital:"₹500 Cr+", career_url:"https://careers.smartrecruiters.com/Freshworks", ats:"SmartRecruiters", status:"Active" },
    { cin:"U72900KA2019PTC125488", legal_name:"SWIGGY BUNDL TECHNOLOGIES PRIVATE LIMITED", name:"SWIGGY BUNDL TECHNOLOGIES PRIVATE LIMITED", brand:"Swiggy", domain:"swiggy.com", roc:"ROC Bangalore", incorporated:2014, company_class:"Private", capital:"₹200 Cr+", career_url:"https://careers.smartrecruiters.com/Swiggy", ats:"SmartRecruiters", status:"Active" },
    { cin:"U74999KA2018PTC118991", legal_name:"DREAMPLUG TECHNOLOGIES PRIVATE LIMITED", name:"DREAMPLUG TECHNOLOGIES PRIVATE LIMITED", brand:"CRED", domain:"cred.club", roc:"ROC Bangalore", incorporated:2018, company_class:"Private", capital:"₹150 Cr+", career_url:"https://jobs.lever.co/cred", ats:"Lever", status:"Active" },
    { cin:"U72900KA2019PTC134567", legal_name:"MEESHO SUPPLY CHAIN PRIVATE LIMITED", name:"MEESHO SUPPLY CHAIN PRIVATE LIMITED", brand:"Meesho", domain:"meesho.com", roc:"ROC Bangalore", incorporated:2015, company_class:"Private", capital:"₹100 Cr+", career_url:"https://jobs.lever.co/meesho", ats:"Lever", status:"Active" },
    { cin:"U74999KA2015PTC082455", legal_name:"GROWW INVEST TECH PRIVATE LIMITED", name:"GROWW INVEST TECH PRIVATE LIMITED", brand:"Groww", domain:"groww.in", roc:"ROC Bangalore", incorporated:2016, company_class:"Private", capital:"₹100 Cr+", career_url:"https://boards.greenhouse.io/groww", ats:"Greenhouse", status:"Active" },
    { cin:"U72900KA2011PTC058998", legal_name:"INMOBI PRIVATE LIMITED", name:"INMOBI PRIVATE LIMITED", brand:"InMobi", domain:"inmobi.com", roc:"ROC Bangalore", incorporated:2007, company_class:"Private", capital:"₹300 Cr+", career_url:"https://boards.greenhouse.io/inmobi", ats:"Greenhouse", status:"Active" },
    { cin:"L72200KA1981PLC004276", legal_name:"INFOSYS LIMITED", name:"INFOSYS LIMITED", brand:"Infosys", domain:"infosys.com", roc:"ROC Bangalore", incorporated:1981, company_class:"Public", capital:"₹1,000 Cr+", career_url:"https://career.infosys.com/joblist", ats:"Custom", status:"Active" },
    { cin:"U93090KA2014PTC078949", legal_name:"PHONEPE PRIVATE LIMITED", name:"PHONEPE PRIVATE LIMITED", brand:"PhonePe", domain:"phonepe.com", roc:"ROC Bangalore", incorporated:2015, company_class:"Private", capital:"₹200 Cr+", career_url:"https://www.phonepe.com/careers", ats:"Custom", status:"Active" },
    { cin:"U72900DL2010PTC206375", legal_name:"ZOMATO LIMITED", name:"ZOMATO LIMITED", brand:"Zomato", domain:"zomato.com", roc:"ROC Delhi", incorporated:2010, company_class:"Public", capital:"₹300 Cr+", career_url:"https://www.eternal.com/careers", ats:"Custom", status:"Active" },
    { cin:"U51909KA2011PTC060815", legal_name:"FLIPKART INDIA PRIVATE LIMITED", name:"FLIPKART INDIA PRIVATE LIMITED", brand:"Flipkart", domain:"flipkart.com", roc:"ROC Bangalore", incorporated:2011, company_class:"Private", capital:"₹250 Cr+", career_url:"https://www.flipkartcareers.com", ats:"Custom", status:"Active" },
    { cin:"U65990KA2019PTC124778", legal_name:"EPIFI TECHNOLOGIES PRIVATE LIMITED", name:"EPIFI TECHNOLOGIES PRIVATE LIMITED", brand:"Fi Money", domain:"fi.money", roc:"ROC Bangalore", incorporated:2019, company_class:"Private", capital:"₹100 Cr+", career_url:"https://jobs.lever.co/epifi", ats:"Lever", status:"Active" },
    { cin:"U63030KA2014PTC077962", legal_name:"PORTER LOGISTICS PRIVATE LIMITED", name:"PORTER LOGISTICS PRIVATE LIMITED", brand:"Porter", domain:"porter.in", roc:"ROC Bangalore", incorporated:2014, company_class:"Private", capital:"₹200 Cr+", career_url:"https://boards.greenhouse.io/porter", ats:"Greenhouse", status:"Active" },
    { cin:"U72900KA2011PTC058999", legal_name:"GLANCE DIGITAL EXPERIENCE PVT LTD", name:"GLANCE DIGITAL EXPERIENCE PVT LTD", brand:"Glance", domain:"glance.com", roc:"ROC Bangalore", incorporated:2019, company_class:"Private", capital:"₹150 Cr+", career_url:"https://boards.greenhouse.io/glance", ats:"Greenhouse", status:"Active" },
    { cin:"U74999DL2015PTC281154", legal_name:"CARS24 SERVICES PRIVATE LIMITED", name:"CARS24 SERVICES PRIVATE LIMITED", brand:"Cars24", domain:"cars24.com", roc:"ROC Delhi", incorporated:2015, company_class:"Private", capital:"₹150 Cr+", career_url:"https://careers.smartrecruiters.com/Cars24", ats:"SmartRecruiters", status:"Active" },
    { cin:"U72900MH2013PTC246588", legal_name:"NOBROKER TECHNOLOGIES SOLUTIONS PVT LTD", name:"NOBROKER TECHNOLOGIES SOLUTIONS PVT LTD", brand:"NoBroker", domain:"nobroker.com", roc:"ROC Bangalore", incorporated:2013, company_class:"Private", capital:"₹100 Cr+", career_url:"https://careers.smartrecruiters.com/NoBroker", ats:"SmartRecruiters", status:"Active" },
    { cin:"U72900KA2018PTC109577", legal_name:"KARNA LEARNING PRIVATE LIMITED", name:"KARNA LEARNING PRIVATE LIMITED", brand:"Unacademy", domain:"unacademy.com", roc:"ROC Bangalore", incorporated:2015, company_class:"Private", capital:"₹100 Cr+", career_url:"https://careers.smartrecruiters.com/Unacademy", ats:"SmartRecruiters", status:"Active" },
    { cin:"L72200MH1968PLC014594", legal_name:"WIPRO LIMITED", name:"WIPRO LIMITED", brand:"Wipro", domain:"wipro.com", roc:"ROC Bangalore", incorporated:1945, company_class:"Public", capital:"₹1,200 Cr+", career_url:"https://careers.wipro.com", ats:"SuccessFactors", status:"Active" },
    { cin:"L72200MH1969PLC014636", legal_name:"HCL TECHNOLOGIES LIMITED", name:"HCL TECHNOLOGIES LIMITED", brand:"HCL Tech", domain:"hcltech.com", roc:"ROC Noida", incorporated:1991, company_class:"Public", capital:"₹800 Cr+", career_url:"https://www.hcltech.com/careers", ats:"Custom", status:"Active" },
    { cin:"U72900KA2008PTC046312", legal_name:"ZOHO CORPORATION PRIVATE LIMITED", name:"ZOHO CORPORATION PRIVATE LIMITED", brand:"Zoho", domain:"zoho.com", roc:"ROC Chennai", incorporated:1996, company_class:"Private", capital:"₹1,000 Cr+", career_url:"https://www.zoho.com/careers.html", ats:"Custom", status:"Active" },
    { cin:"U74999MH2019PTC325078", legal_name:"BROWSERSTACK SOFTWARE PRIVATE LIMITED", name:"BROWSERSTACK SOFTWARE PRIVATE LIMITED", brand:"BrowserStack", domain:"browserstack.com", roc:"ROC Mumbai", incorporated:2011, company_class:"Private", capital:"₹200 Cr+", career_url:"https://www.browserstack.com/careers", ats:"Custom", status:"Active" },
    { cin:"U72200MH2015PTC268901", legal_name:"DELHIVERY PRIVATE LIMITED", name:"DELHIVERY PRIVATE LIMITED", brand:"Delhivery", domain:"delhivery.com", roc:"ROC Gurugram", incorporated:2011, company_class:"Public", capital:"₹200 Cr+", career_url:"https://www.delhivery.com/careers", ats:"Custom", status:"Active" },
    { cin:"U85100KA2014PTC077102", legal_name:"CURE FIT HEALTHCARE PRIVATE LIMITED", name:"CURE FIT HEALTHCARE PRIVATE LIMITED", brand:"Cult.fit", domain:"cult.fit", roc:"ROC Bangalore", incorporated:2016, company_class:"Private", capital:"₹500 Cr+", career_url:"https://www.cult.fit/careers", ats:"Custom", status:"Active" },
    { cin:"U80904KA2015PTC082201", legal_name:"UPGRAD EDUCATION PRIVATE LIMITED", name:"UPGRAD EDUCATION PRIVATE LIMITED", brand:"upGrad", domain:"upgrad.com", roc:"ROC Mumbai", incorporated:2015, company_class:"Private", capital:"₹500 Cr+", career_url:"https://www.upgrad.com/careers", ats:"Custom", status:"Active" }
  ],

  jobs: [
    // ── FRESHERS / ENTRY LEVEL ──
    { id:"JOB-F01", title:"Graduate Engineer Trainee (GET) — Software", company_cin:"L72200MH1995PLC085624", company_name:"Tata Consultancy Services Limited", brand:"TCS", location:"Bengaluru / Hyderabad / Pune", exp_level:"entry_level", exp_years:0, exp_display:"0–1 Yr (Freshers 2025/2026 Batch)", salary:"₹4.5–7 LPA", category:"Software Development", department:"Engineering", ats:"Custom/iON", direct_url:"https://www.tcs.com/careers/india/tcs-all-india-nqt-hiring", apply_url:"https://www.tcs.com/careers/india/tcs-all-india-nqt-hiring", posted_date:"2026-09-15", skills:["Java","Python","SQL","Data Structures"], description:"Hiring 2025/2026 Engineering & MCA graduates for cloud application development, Java microservices, and AI engineering tracks at TCS." },
    { id:"JOB-F02", title:"Junior Frontend Developer — React / Next.js", company_cin:"U74999KA2018PTC118991", company_name:"Dreamplug Technologies Pvt Ltd", brand:"CRED", location:"Bengaluru, Karnataka", exp_level:"entry_level", exp_years:1, exp_display:"0–2 Yrs", salary:"₹12–18 LPA", category:"Software Development", department:"Frontend Engineering", ats:"Lever", direct_url:"https://jobs.lever.co/cred", apply_url:"https://jobs.lever.co/cred", posted_date:"2026-09-17", skills:["React","TypeScript","CSS3","Next.js"], description:"Join CRED's product engineering team building high-performance consumer app UI. Strong frontend fundamentals required." },
    { id:"JOB-F03", title:"Associate Product Analyst", company_cin:"U72900KA2019PTC134567", company_name:"Meesho Supply Chain Pvt Ltd", brand:"Meesho", location:"Bengaluru (Hybrid)", exp_level:"entry_level", exp_years:0, exp_display:"0–2 Yrs (Campus / Freshers)", salary:"₹10–15 LPA", category:"Data Analytics & AI", department:"Product & Analytics", ats:"Lever", direct_url:"https://jobs.lever.co/meesho", apply_url:"https://jobs.lever.co/meesho", posted_date:"2026-09-16", skills:["SQL","Python","Tableau","Excel"], description:"Analyse e-commerce funnels, user conversion, and supply chain data at Meesho. Ideal for fresh graduates with strong SQL background." },
    { id:"JOB-F04", title:"Systems Engineer Trainee — Freshers", company_cin:"L72200KA1981PLC004276", company_name:"Infosys Limited", brand:"Infosys", location:"Pune / Hyderabad / Mysore", exp_level:"entry_level", exp_years:0, exp_display:"0–1 Yr (Freshers)", salary:"₹4–6.5 LPA", category:"IT & Infrastructure", department:"Engineering", ats:"Custom", direct_url:"https://career.infosys.com/joblist", apply_url:"https://career.infosys.com/joblist", posted_date:"2026-09-14", skills:["C++","Java","Linux","RDBMS"], description:"Entry-level software engineering programme at Infosys Global Education Center. Comprehensive training in Full Stack and Cloud." },
    { id:"JOB-F05", title:"Junior Backend Engineer — Go / Node.js", company_cin:"U72200KA2013PTC097332", company_name:"Razorpay Software Pvt Ltd", brand:"Razorpay", location:"Bengaluru / Remote", exp_level:"entry_level", exp_years:1, exp_display:"0–2 Yrs", salary:"₹14–20 LPA", category:"Software Development", department:"Payments Engineering", ats:"Greenhouse", direct_url:"https://boards.greenhouse.io/razorpaysoftwareprivatelimited", apply_url:"https://boards.greenhouse.io/razorpaysoftwareprivatelimited", posted_date:"2026-09-15", skills:["Golang","Node.js","PostgreSQL","Redis"], description:"Join Razorpay's Core Payments team handling millions of transactions daily. Build scalable microservices under senior mentorship." },
    { id:"JOB-F06", title:"Customer Success Associate", company_cin:"U72900TN2010PLC075256", company_name:"Freshworks Inc India Pvt Ltd", brand:"Freshworks", location:"Chennai, Tamil Nadu", exp_level:"entry_level", exp_years:1, exp_display:"0–2 Yrs", salary:"₹5–8 LPA", category:"Customer Success", department:"Customer Experience", ats:"SmartRecruiters", direct_url:"https://careers.smartrecruiters.com/Freshworks", apply_url:"https://careers.smartrecruiters.com/Freshworks", posted_date:"2026-09-13", skills:["Communication","CRM","SaaS","Problem Solving"], description:"Work with enterprise customers on Freshdesk onboarding, adoption, and support. Great entry point into SaaS." },
    { id:"JOB-F07", title:"Data Analyst Trainee", company_cin:"U74999KA2015PTC082455", company_name:"Groww Invest Tech Pvt Ltd", brand:"Groww", location:"Bengaluru, Karnataka", exp_level:"entry_level", exp_years:0, exp_display:"0–1 Yr (Freshers)", salary:"₹8–12 LPA", category:"Data Analytics & AI", department:"Data Science", ats:"Greenhouse", direct_url:"https://boards.greenhouse.io/groww", apply_url:"https://boards.greenhouse.io/groww", posted_date:"2026-09-12", skills:["Python","SQL","Pandas","Power BI"], description:"Analyse financial and user behaviour data to help Groww improve investment products for millions of users." },
    { id:"JOB-F08", title:"QA Engineer Trainee", company_cin:"U72900KA2019PTC125488", company_name:"Swiggy Bundl Technologies Pvt Ltd", brand:"Swiggy", location:"Bengaluru, Karnataka", exp_level:"entry_level", exp_years:1, exp_display:"0–2 Yrs", salary:"₹7–11 LPA", category:"Quality Assurance", department:"Engineering — QA", ats:"SmartRecruiters", direct_url:"https://careers.smartrecruiters.com/Swiggy", apply_url:"https://careers.smartrecruiters.com/Swiggy", posted_date:"2026-09-11", skills:["Selenium","Playwright","Python","API Testing"], description:"Automate end-to-end test suites for Swiggy's food delivery and grocery apps." },
    { id:"JOB-F09", title:"Product Designer — UI/UX (Fresher)", company_cin:"U65990KA2019PTC124778", company_name:"EpiFi Technologies Pvt Ltd", brand:"Fi Money", location:"Bengaluru, Karnataka", exp_level:"entry_level", exp_years:1, exp_display:"0–2 Yrs", salary:"₹10–16 LPA", category:"Design", department:"Product Design", ats:"Lever", direct_url:"https://jobs.lever.co/epifi", apply_url:"https://jobs.lever.co/epifi", posted_date:"2026-09-10", skills:["Figma","User Research","Prototyping","Design Systems"], description:"Shape the financial experience for Fi Money users. Strong portfolio of mobile-first product design required." },
    { id:"JOB-F10", title:"Operations Executive — Delivery", company_cin:"U63030KA2014PTC077962", company_name:"Porter Logistics Pvt Ltd", brand:"Porter", location:"Multiple Cities — Pan India", exp_level:"entry_level", exp_years:0, exp_display:"Freshers Welcome", salary:"₹3.5–5.5 LPA", category:"Operations", department:"City Operations", ats:"Greenhouse", direct_url:"https://boards.greenhouse.io/porter", apply_url:"https://boards.greenhouse.io/porter", posted_date:"2026-09-09", skills:["Excel","Ops Management","Vendor Management","Communication"], description:"Run daily city operations for Porter's last-mile delivery network. Ground-up operations role with fast growth path." },

    // ── EXPERIENCED ──
    { id:"JOB-E01", title:"Senior Backend Architect — Distributed Systems", company_cin:"U72200KA2013PTC097332", company_name:"Razorpay Software Pvt Ltd", brand:"Razorpay", location:"Bengaluru, Karnataka", exp_level:"experienced", exp_years:6, exp_display:"5–8 Yrs (Senior / Lead)", salary:"₹38–55 LPA + ESOPs", category:"Software Development", department:"Payments Engineering", ats:"Greenhouse", direct_url:"https://boards.greenhouse.io/razorpaysoftwareprivatelimited", apply_url:"https://boards.greenhouse.io/razorpaysoftwareprivatelimited", posted_date:"2026-09-17", skills:["Java","Distributed Systems","Kafka","AWS"], description:"Lead architecture for high-throughput payment processing pipelines handling $10B+ annual transactions." },
    { id:"JOB-E02", title:"Staff Data Scientist — Recommendations", company_cin:"U72900KA2011PTC058998", company_name:"InMobi Pvt Ltd", brand:"InMobi", location:"Bengaluru, Karnataka", exp_level:"experienced", exp_years:5, exp_display:"5–8 Yrs", salary:"₹35–50 LPA", category:"Data Analytics & AI", department:"ML Platform", ats:"Greenhouse", direct_url:"https://boards.greenhouse.io/inmobi", apply_url:"https://boards.greenhouse.io/inmobi", posted_date:"2026-09-16", skills:["PyTorch","ML Ops","Recommendation Systems","Spark"], description:"Build next-gen ad recommendation systems serving 1B+ users across InMobi's global ad platform." },
    { id:"JOB-E03", title:"Principal Product Manager — Payments", company_cin:"U72200MH2007PTC173821", company_name:"One97 Communications Limited", brand:"Paytm", location:"Noida / Delhi NCR", exp_level:"experienced", exp_years:7, exp_display:"7–12 Yrs (Principal)", salary:"₹50–75 LPA + Equity", category:"Product Management", department:"Payments Product", ats:"Lever", direct_url:"https://jobs.lever.co/paytm", apply_url:"https://jobs.lever.co/paytm", posted_date:"2026-09-17", skills:["Product Strategy","Fintech","UPI","UX"], description:"Own product roadmap for Paytm Payment Gateway and international payouts. 7+ years fintech product leadership required." },
    { id:"JOB-E04", title:"Engineering Manager — Growth Platform", company_cin:"U72900TN2010PLC075256", company_name:"Freshworks Inc India Pvt Ltd", brand:"Freshworks", location:"Chennai / Bengaluru (Hybrid)", exp_level:"experienced", exp_years:8, exp_display:"7–12 Yrs (EM)", salary:"₹45–70 LPA", category:"Software Development", department:"Growth Engineering", ats:"SmartRecruiters", direct_url:"https://careers.smartrecruiters.com/Freshworks", apply_url:"https://careers.smartrecruiters.com/Freshworks", posted_date:"2026-09-15", skills:["People Management","Ruby on Rails","Microservices","AWS"], description:"Lead a team of 8+ engineers building Freshworks' growth and experimentation platform for 60,000+ global customers." },
    { id:"JOB-E05", title:"Senior DevOps Engineer — Kubernetes", company_cin:"U72900KA2019PTC125488", company_name:"Swiggy Bundl Technologies Pvt Ltd", brand:"Swiggy", location:"Bengaluru, Karnataka", exp_level:"experienced", exp_years:5, exp_display:"4–7 Yrs", salary:"₹30–45 LPA", category:"DevOps & Cloud", department:"Platform Engineering", ats:"SmartRecruiters", direct_url:"https://careers.smartrecruiters.com/Swiggy", apply_url:"https://careers.smartrecruiters.com/Swiggy", posted_date:"2026-09-14", skills:["Kubernetes","Docker","Terraform","Prometheus"], description:"Manage Swiggy's platform infrastructure scaling across 50,000+ nodes during peak order surges." },
    { id:"JOB-E06", title:"Lead AI / ML Research Scientist", company_cin:"L72200MH1995PLC085624", company_name:"Tata Consultancy Services Limited", brand:"TCS", location:"Hyderabad, Telangana", exp_level:"experienced", exp_years:4, exp_display:"4–8 Yrs (Mid/Senior)", salary:"₹25–40 LPA", category:"Data Analytics & AI", department:"AI Research", ats:"Custom/iON", direct_url:"https://www.tcs.com/careers", apply_url:"https://www.tcs.com/careers", posted_date:"2026-09-14", skills:["PyTorch","LLMs","Generative AI","NLP"], description:"Drive Enterprise GenAI and Large Language Model fine-tuning for global Fortune 500 clients at TCS Research." },
    { id:"JOB-E07", title:"Senior Mobile Engineer — Android (Kotlin)", company_cin:"U74999KA2018PTC118991", company_name:"Dreamplug Technologies Pvt Ltd", brand:"CRED", location:"Bengaluru, Karnataka", exp_level:"experienced", exp_years:4, exp_display:"3–6 Yrs", salary:"₹30–50 LPA + ESOPs", category:"Software Development", department:"Mobile Engineering", ats:"Lever", direct_url:"https://jobs.lever.co/cred", apply_url:"https://jobs.lever.co/cred", posted_date:"2026-09-13", skills:["Kotlin","Android Jetpack","Coroutines","System Design"], description:"Build CRED's flagship Android app used by India's top credit card holders. Deep Kotlin experience required." },
    { id:"JOB-E08", title:"Head of Growth Marketing", company_cin:"U74999KA2015PTC082455", company_name:"Groww Invest Tech Pvt Ltd", brand:"Groww", location:"Bengaluru, Karnataka", exp_level:"experienced", exp_years:6, exp_display:"5–9 Yrs", salary:"₹35–55 LPA", category:"Marketing", department:"Growth & Marketing", ats:"Greenhouse", direct_url:"https://boards.greenhouse.io/groww", apply_url:"https://boards.greenhouse.io/groww", posted_date:"2026-09-12", skills:["Growth Marketing","SEO","Performance Marketing","Analytics"], description:"Own Groww's user acquisition and activation funnels. Lead a team of 10 driving growth for 50M+ registered investors." },
    { id:"JOB-E09", title:"Senior iOS Engineer (Swift)", company_cin:"U72900KA2011PTC058999", company_name:"Glance Digital Experience Pvt Ltd", brand:"Glance", location:"Bengaluru, Karnataka", exp_level:"experienced", exp_years:4, exp_display:"3–6 Yrs", salary:"₹28–45 LPA", category:"Software Development", department:"Mobile Engineering", ats:"Greenhouse", direct_url:"https://boards.greenhouse.io/glance", apply_url:"https://boards.greenhouse.io/glance", posted_date:"2026-09-11", skills:["Swift","SwiftUI","Core Data","ARKit"], description:"Build Glance's content discovery experience on iOS, reaching 200M+ lock screen users globally." },
    { id:"JOB-E10", title:"Director of Engineering — Fintech Platform", company_cin:"U65990KA2019PTC124778", company_name:"EpiFi Technologies Pvt Ltd", brand:"Fi Money", location:"Bengaluru, Karnataka", exp_level:"experienced", exp_years:10, exp_display:"8–14 Yrs (Director)", salary:"₹60–90 LPA + Equity", category:"Software Development", department:"Engineering Leadership", ats:"Lever", direct_url:"https://jobs.lever.co/epifi", apply_url:"https://jobs.lever.co/epifi", posted_date:"2026-09-10", skills:["Engineering Leadership","System Design","Fintech","Team Building"], description:"Lead Fi Money's core banking and fintech platform engineering teams. Shape the technical direction of India's fastest growing neobank." }
  ]
};
